services:
  docs:
    image: ifcb_data_share_manager_local_docs
    container_name: ifcb_data_share_manager_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ifcb_data_share_manager:/app/ifcb_data_share_manager:z
    ports:
      - '9000:9000'
    command: /start-docs
